services:
  postgres:
    container_name: postgres
    image: "pgvector/pgvector:pg17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nwa
      POSTGRES_PASSWORD: nwa
      POSTGRES_DB: orchestrator-core
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./docker/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username",
          "nwa",
          "--dbname",
          "orchestrator-core",
        ]
      interval: "3s"
      timeout: "2s"
      retries: 20
      start_period: "5s"

  redis:
    container_name: redis
    image: docker.io/redis:8-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck:
      test: '[ $$(redis-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    env_file:
      - ./docker/redis/redis.env
      - path: ./docker/overrides/redis/redis.env
        required: false
    #volumes:
    #  - netbox-redis-cache-data:/data

  embeddings:
    container_name: embeddings
    platform: linux/amd64
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    command: --model-id sentence-transformers/all-MiniLM-L6-v2
    profiles:
      - embeddings
    env_file:
      - ./docker/embeddings/embeddings.env
      - path: ./docker/overrides/embeddings/embeddings.env
        required: false
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ui-library-builder:
    image: node:18
    #image: node:20
    working_dir: /repo
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../orchestrator-ui-library:/repo
      - lib_root_node_modules:/repo/node_modules
      - lib_pkg_node_modules:/repo/packages/orchestrator-ui-components/node_modules
      # Keep .turbo from writing to the host
      - lib_turbo:/repo/.turbo
      - lib_dist:/out
    # TODO: this could be improved to rebuild all four packages
    command: >
      sh -c "npm ci &&
             npx turbo run build &&
             cd packages/orchestrator-ui-components &&
             npx tsup --watch --out-dir /out src/index.ts"
    healthcheck:
      test: ["CMD", "test", "-f", "/out/index.js"]
      interval: 5s
      retries: 60


  orchestrator-ui:
    container_name: orchestrator-ui
    build:
      context: ../example-orchestrator-ui
      target: builder
    entrypoint: ["npm", "run", "dev"]
    volumes:
      # Override Next.js configuration to react to changes in orchestrator-ui-components dist/ 
      - ./docker/orchestrator-ui/next.config.js:/app/next.config.js
      # Mount orchestrator-ui-components dist/ from ui-builder
      - type: volume
        source: lib_dist
        target: /app/node_modules/@orchestrator-ui/orchestrator-ui-components/dist
        volume:
          # Prevents previous contents of dist/ from appearing if we mount an empty directory
          nocopy: true
      #TODO bind-mount ../example-orchestrator-ui
    working_dir: /app
    env_file:
      - ./docker/orchestrator-ui/orchestrator-ui.env
      - path: ./docker/overrides/orchestrator-ui/orchestrator-ui.env
        required: false
    # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    #ports:
    #  - "3000:3000"
    network_mode: "service:keycloak"
    depends_on:
      ui-library-builder:
        condition: service_healthy
      orchestrator:
        condition: service_started
      keycloak:
        condition: service_started

  orchestrator:
    container_name: orchestrator
    image: ${ORCH_BACKEND_TAG:-ghcr.io/workfloworchestrator/orchestrator-core:latest}
    env_file:
      - ./docker/orchestrator/orchestrator.env
      - path: ./docker/overrides/orchestrator/orchestrator.env
        required: false
    # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    #ports:
    #  - "8080:8080"
    #  - "5678:5678" #Enable Python debugger

    # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    network_mode: "service:keycloak"
    volumes:
      - ./db:/home/orchestrator/db
      - ./workflows:/home/orchestrator/workflows
      - ./products:/home/orchestrator/products
      - ./migrations:/home/orchestrator/migrations
      - ./docker:/home/orchestrator/etc
      - ./main.py:/home/orchestrator/main.py
      - ./wsgi.py:/home/orchestrator/wsgi.py
      - ./settings.py:/home/orchestrator/settings.py
      - ./graphql_utils:/home/orchestrator/graphql_utils
      - ./utils:/home/orchestrator/utils
      - ./services:/home/orchestrator/services
      - ./pyproject.toml:/home/orchestrator/pyproject.toml
      - ./alembic.ini:/home/orchestrator/alembic.ini
      - ./translations:/home/orchestrator/translations
      - ./docker/orchestrator/.bashrc:/home/orchestrator/.bashrc
      # CORE_DIR should be specified in ./.env.
      # You can set a custom orchestrator-core repo to install from source, like ../orchestrator-core
      # OR you can just clone the repo to docker/overrides/orchestrator-core
      # CORE_OVERRIDE (set in docker/orchestrator/orchestrator.env) specifies the in-container path
      # from which the entrypoint should (install and watch) orchestrator-core from
      - "${CORE_DIR:-./docker/overrides/orchestrator-core}:/home/orchestrator/orchestrator-core"
    entrypoint: ["/home/orchestrator/etc/orchestrator/entrypoint.sh"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      embeddings:
        condition: service_healthy
        required: false
      keycloak:
        condition: service_started
    healthcheck:
      start_period: 15s
      timeout: 5s
      interval: 5s
      retries: 20
      test: /home/orchestrator/etc/orchestrator/is_healthy.py

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    # To debug or generate user exports, uncomment the below, comment out "command", and uncomment the export volume below
    #entrypoint: tail -f /dev/null
    #Then `export --dir /opt/keycloak/data/export --realm orchestrator --users same_file` inside the container
    command: start-dev --import-realm --http-port=8085
    ports:
      # Keycloak itself
      - "127.0.0.1:8085:8085"
      # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
      - "127.0.0.1:3000:3000" # Orch UI
      # Maybe backend doesn't need this?? Is it just getting data from the JWT?
      # I think it actually does need this to fetch a cert
      - "127.0.0.1:8080:8080" # Orch backend
      - "127.0.0.1:5678:5678" # Orch backend debugger
    env_file:
      - ./docker/keycloak/keycloak.env
    volumes:
      # Uncomment if you need to generate new user exports
      #- ./keycloak_export:/opt/keycloak/data/export
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  db-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  # For binding UI builder into UI container
  lib_root_node_modules:
  lib_pkg_node_modules:
  lib_turbo:
  lib_dist:
  #TODO additional volumes for preventing writes back to the host FS. If possible, should not persist.
