services:
  postgres:
    container_name: postgres
    image: "pgvector/pgvector:pg17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nwa
      POSTGRES_PASSWORD: nwa
      POSTGRES_DB: orchestrator-core
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./docker/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username",
          "nwa",
          "--dbname",
          "orchestrator-core",
        ]
      interval: "3s"
      timeout: "2s"
      retries: 20
      start_period: "5s"

  redis:
    container_name: redis
    image: docker.io/redis:8-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    healthcheck:
      test: '[ $$(redis-cli --pass "$${REDIS_PASSWORD}" ping) = ''PONG'' ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    env_file:
      - ./docker/redis/redis.env
      - path: ./docker/overrides/redis/redis.env
        required: false
    #volumes:
    #  - netbox-redis-cache-data:/data

  #TODO can this go away?
  embeddings:
    container_name: embeddings
    platform: linux/amd64
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8
    command: --model-id sentence-transformers/all-MiniLM-L6-v2
    profiles:
      - embeddings
    env_file:
      - ./docker/embeddings/embeddings.env
      - path: ./docker/overrides/embeddings/embeddings.env
        required: false
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  orchestrator-ui:
    container_name: orchestrator-ui
    #TODO this is what I need to tweak to get separate well-known URLs
    image: ${ORCH_UI_TAG:-ghcr.io/workfloworchestrator/example-orchestrator-ui:latest}
    volumes:
      # Bind-mount the example-orchestrator-ui repo source, which the container will watch for changes
      - ../example-orchestrator-ui:/app
      # Override the Next.js configuration, so we react to changes in the orchestrator-ui-library node module's dist folder
      - ./docker/orchestrator-ui/next.config.js:/app/next.config.js
      # Bind-mount the dist directly from orchestrator-ui-library into node_modules
      - ../orchestrator-ui-library/packages/orchestrator-ui-components/dist:/app/node_modules/@orchestrator-ui/orchestrator-ui-components/dist
      # Bind-mount src as well to avioid any potential confusion
      - ../orchestrator-ui-library/packages/orchestrator-ui-components/src:/app/node_modules/@orchestrator-ui/orchestrator-ui-components/src
      # Not all dependencies are present in the node_modules subfolder assemled by orchestrator-ui-library,
      # so we use the one assembled by example-orchestrator-ui
      - ../example-orchestrator-ui/node_modules/@orchestrator-ui/orchestrator-ui-components/node_modules:/app/node_modules/@orchestrator-ui/orchestrator-ui-components/node_modules
    working_dir: /app
    entrypoint: ["npm", "run", "dev"]
    env_file:
      - ./docker/orchestrator-ui/orchestrator-ui.env
      - path: ./docker/overrides/orchestrator-ui/orchestrator-ui.env
        required: false
    #ports:
    #  - "3000:3000"
    #  Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    network_mode: "service:keycloak"
    depends_on:
      orchestrator:
        condition: service_started
      keycloak:
        condition: service_started

  orchestrator:
    container_name: orchestrator
    image: ${ORCH_BACKEND_TAG:-ghcr.io/workfloworchestrator/orchestrator-core:latest}
    env_file:
      - ./docker/orchestrator/orchestrator.env
      - path: ./docker/overrides/orchestrator/orchestrator.env
        required: false
    # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    #ports:
    #  - "8080:8080"
    #  - "5678:5678" #Enable Python debugger

    # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
    network_mode: "service:keycloak"
    volumes:
      - ./db:/home/orchestrator/db
      - ./workflows:/home/orchestrator/workflows
      - ./products:/home/orchestrator/products
      - ./migrations:/home/orchestrator/migrations
      - ./docker:/home/orchestrator/etc
      - ./main.py:/home/orchestrator/main.py
      - ./wsgi.py:/home/orchestrator/wsgi.py
      - ./settings.py:/home/orchestrator/settings.py
      - ./graphql_utils:/home/orchestrator/graphql_utils
      - ./utils:/home/orchestrator/utils
      - ./services:/home/orchestrator/services
      - ./pyproject.toml:/home/orchestrator/pyproject.toml
      - ./alembic.ini:/home/orchestrator/alembic.ini
      - ./translations:/home/orchestrator/translations
      - ./docker/orchestrator/.bashrc:/home/orchestrator/.bashrc
      # CORE_DIR should be specified in ./.env.
      # You can set a custom orchestrator-core repo to install from source, like ../orchestrator-core
      # OR you can just clone the repo to docker/overrides/orchestrator-core
      # CORE_OVERRIDE (set in docker/orchestrator/orchestrator.env) specifies the in-container path
      # from which the entrypoint should (install and watch) orchestrator-core from
      - "${CORE_DIR:-./docker/overrides/orchestrator-core}:/home/orchestrator/orchestrator-core"
    entrypoint: ["/home/orchestrator/etc/orchestrator/entrypoint.sh"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      embeddings:
        condition: service_healthy
        required: false
      keycloak:
        condition: service_started
    healthcheck:
      start_period: 15s
      timeout: 5s
      interval: 5s
      retries: 20
      test: /home/orchestrator/etc/orchestrator/is_healthy.py

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    #TODO debugging for generating user exports
    #entrypoint: tail -f /dev/null
    #Then `export --dir /opt/keycloak/data/export --realm orchestrator --users same_file` inside the container
    command: start-dev --import-realm --http-port=8085
    ports:
      # Keycloak itself
      - "127.0.0.1:8085:8085"
      # Awful hack because NextAuth doesn't accept distinct well-known URIs for browser/client and its backend
      - "127.0.0.1:3000:3000" # Orch UI
      # Maybe backend doesn't need this?? Is it just getting data from the JWT?
      # I think it actually does need this to fetch a cert
      - "127.0.0.1:8080:8080" # Orch backend
      - "127.0.0.1:5678:5678" # Orch backend debugger
    env_file:
      - ./docker/keycloak/keycloak.env
    volumes:
      #TODO debugging for generating user exports
      #- ./keycloak_export:/opt/keycloak/data/export
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro

volumes:
  db-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
